include classpath("application.conf")

node-address {
  protocol = http
  host = elasticmq
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

rest-stats {
  enabled = false
}

queues {
  prdal-jobs {
    defaultVisibilityTimeout = 60 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "prdal-jobs-dlq"
      maxReceiveCount = 3
    }
  }
  prdal-jobs-dlq {
    defaultVisibilityTimeout = 60 seconds
  }
}
